### ISSUE TITLE
[NEW] Improve Analytics tracking

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1455]
## Description

- [x] Make an option in "Preferences" to enable/disable the Analytics tracking. It's by default `true`.
- [x] Integrate with Google Analytics for Firebase (GA)
- [x] Make sure Answers (from Fabric) is integrated/installed
- [x] Call the following events:
  - [x] Login
    - [x] For Answer (Answers has a default method for that)
    - [x] For GA (you can use `login`)
  - [x] Signup
    - [x] For Answer (Answers has a default method for that)
    - [x] For GA (you can use `sign_up `)
  - [x] `screen_view`, params: [`screen`: screen name (can be a generic class name)]
    - [x] For Answer
    - [x] For GA
  - [x] `message_sent`, params: [`subscription_type`: just the type of the subscription (`c`, `d` or `p` ), `server`: just the host part]
    - [x] For Answer
    - [x] For GA
  - [x] `media_upload`, params: [`subscription_type`: just the type of the subscription (`c`, `d` or `p` ), `media_type`: mimetype of the file]
    - [x] For Answer
    - [x] For GA
  - [x] `reaction`, params: [`subscription_type`: just the type of the subscription (`c`, `d` or `p` )]
    - [x] For Answer
    - [x] For GA
  - [x] `server_switch`, params: [`server_url`, `server_count`]
    - [x] For Answer
    - [x] For GA
