### ISSUE TITLE
[Improvement] Chatroom files UI redesign, search by author, date filename,

### ISSUE THREAD

**Issue by Adizbek** [RocketChat/Rocket.Chat.Android#2255]
## TODO List

- [ ] Split file types into tabs
- [ ] Allow to download files
- [ ] Allow media files open with external programs
- [ ] Search by author
- [ ] Search by date
- [ ] Search by filename 

![](https://i.imgur.com/8lNppxg.png)

**Soon I will do PR.**
